const SuperSportCar = [
{
        id: 1,
        CompanyName: 'BMW',
        CarName: 'M5 cs',
        Engine: '4.4 li V8',
        Gearbox: '8at',
        PerformanceCar: '627bhp',
        DriveWheel: 'fourWheeldrive',
        TopSpeed: '309 km/h',
        Price: '142000$',
        Acceleration: '0-100 3sec',
        door: 4
      },
      {
        id: 2,
        CompanyName: 'Mercedes-Benz',
        CarName: 'AMG gt 63',
        Engine: '4.0 li v8',
        Gearbox: '9at',
        PerformanceCar: '630 bhp',
        DriveWheel: 'fourWheelDrive',
        TopSpeed: '315 km/h',
        Price: '154500$',
        Acceleration: '0-100 3.2sec',
        door: 4
      },
      {
        id: 3,
        CompanyName: 'AUdi',
        CarName: 'r8 v10 plus',
        Engine: '5.2 li v10',
        Gearbox: '7at',
        PerformanceCar: '602bhp',
        DriveWheel: 'fourWheelDrive',
        TopSpeed: '326 km/h',
        Price: '163900$',
        Acceleration: '0-100 3.3sec',
        door: 2
      },
      {
        id: 4,
        CompanyName: 'Jaguar',
        CarName: 'F type',
        Engine: '5.0 li v8',
        Gearbox: '6mt',
        PerformanceCar: '575 bhp',
        DriveWheel: 'fourWheelDrive',
        TopSpeed: '300 km/h',
        Price: '80000$',
        Acceleration: '0-100 3.5sec',
        door: 2
      },
      {
        id: 5,
        CompanyName: 'Ferrari',
        CarName: 'F40',
        Engine: '2.9 li v8',
        Gearbox: '5mt',
        PerformanceCar: '478 bhp',
        DriveWheel: 'rearWheelDrive',
        TopSpeed: '317 km/h',
        Price: '1500000$',
        Acceleration: '0-100 3.8sec',
        door: 2
      },
      {
        id: 6,
        CompanyName: 'Alfa Romeo',
        CarName: 'Giulia Quadrifoglio',
        Engine: '2.9 li v6',
        Gearbox: '8at',
        PerformanceCar: '505 bhp',
        DriveWheel: 'rearWheelDrive',
        TopSpeed: '307 km/h',
        Price: '90000$',
        Acceleration: '0-100 3.8sec',
        door: 2
      },
      {
        id: 7,
        CompanyName: 'Lamborghini',
        CarName: 'HuracanPerformante',
        Engine: '5.2 li v10',
        Gearbox: '7at',
        PerformanceCar: '640 bhp',
        DriveWheel: 'fourWheelDrive',
        TopSpeed: '325 km/h',
        Price: '300000$',
        Acceleration: '0-100 2.9sec',
        door: 2
      },
      {
        id: 8,
        CompanyName: 'Nissan',
        CarName: 'Skykine r34',
        Engine: '2.6 li I6',
        Gearbox: '6mt',
        PerformanceCar: '280 bhp',
        DriveWheel: 'fourWheelDrive',
        TopSpeed: '256 km/h',
        Price: '120000$',
        Acceleration: '0-100 4.8sec',
        door: 2
      },
      {
        id: 9,
        CompanyName: 'Toyota',
        CarName: 'supra mk4',
        Engine: '3.0 li I6',
        Gearbox: '6mt',
        PerformanceCar: '321 bhp',
        DriveWheel: 'rearWheelDrive',
        TopSpeed: '256 km/h',
        Price: '100000$',
        Acceleration: '0-100 4.7sec',
        door: 2
      },
      {
        id: 10,
        CompanyName: 'Mazda',
        CarName: 'rx7',
        Engine: '1.3 li 2rotor',
        Gearbox: '5mt',
        PerformanceCar: '252 bhp',
        DriveWheel: 'rearWheelDrive',
        TopSpeed: '251 km/h',
        Price: '100000$',
        Acceleration: '0-100 3.8sec',
        door: 2
      }
]
module.exports = SuperSportCar;